version: '3'

services:

  mysql:
    container_name: mysql
    restart: unless-stopped
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --sql_mode=''
    ports:
      - "3306:3306"
    env_file:
      - ./docker/.env
    volumes:
      - datax:/var/lib/mysql
      - ./docker/mysql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    networks:
      - net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    restart: always
    ports:
      - 8080:80
    networks:
      - net


volumes:
  datax:
networks:
  net:
